language: node_js
cache: yarn
node_js:
  - "8.12.0"
before_script:
  - yarn install --pure-lockfile
  - yarn add full-icu
  - yarn check --integrity
script:
  - yarn validate-ci
  - env NODE_ICU_DATA=node_modules/full-icu jest --config=./jest.ci.js --runInBand
